$(document).ready(function(){
	$("#article").click(function(){
		$("#article_lb").slideToggle();
	});
    $("#wechat").click(function(){
		$("#wechat_lb").slideToggle();
	});
	$("#video").click(function(){
		$("#video_lb").slideToggle();
	});
});